# Define the services that make up the application
services:

    # Webserver service configuration
    backend:
        build: .
        container_name: backend
        ports:
            - 8000:80
        volumes:
          - ./:/var/www/html  # Mount the current directory to the container's /var/www/html
          - /var/www/html/vendor  # Mount the /var/www/html/vendor directory
        depends_on:
            - database  # Depend on the db service

    # Database service configuration
    database:
        image: mysql:latest
        container_name: database
        volumes:
            - data:/var/lib/mysql  # Mount a volume for MySQL data storage
        ports:
            - 3306:3306  # Expose port 3306 for MySQL
        environment:
           MYSQL_DATABASE: todo_laravel_api
           MYSQL_ALLOW_EMPTY_PASSWORD: "yes"


# Define a named volume for MySQL data storage
volumes:
    data:
